version: "3.9"

services:
  order-service:
    build: ./order-service
    ports:
      - "${ORDER_SERVICE_PORT:-3001}:3001"
    environment:
      - ZIPKIN_HOST=http://zipkin-exporter:9411
      - SHIPMENT_SERVICE_URL=http://shipment-service:3002
  shipment-service:
    build: ./shipment-service
    ports:
      - "${SHIPMENT_SERVICE_PORT:-3002}:3002"
    environment:
      - ZIPKIN_HOST=http://zipkin-exporter:9411
  zipkin-exporter:
    image: openzipkin/zipkin
    ports:
      - "${ZIPKIN_PORT:-9411}:9411"
