version: "3.9"

services:
  order-service:
    build: ./order-service
    ports:
      - "3001:3001"
    environment:
      - ZIPKIN_HOST=http://zipkin-exporter:9411
      - ORDER_SERVICE_POST=3001
  shipment-service:
    build: ./shipment-service
    ports:
      - "3002:3002"
    environment:
      - ZIPKIN_HOST=http://zipkin-exporter:9411
      - SHIPMENT_SERVICE_POST=3002
  zipkin-exporter:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
